# To subset the input data to estimate subscale alphas, we need a list of char
# vecs containing the col names of the items in each subscale, across forms. We
# start with the "master" char vec, the TOT score (which includes all items),
# and we map `form_acronyms` to create a list of four TOT item vectors, one for
# each form.
TOT_item_names_list <- map(form_acronyms,
                           ~
                             str_c(str_c(.x, "i"), str_pad(
                               as.character(1:50), 2, side = "left", pad = "0"
                             )))

# We define a function that allows us to subset a char vec, from any starting
# position, by any fixed interval length.
nth_element <- function(vector, starting_position, interval) { 
  vector[seq(starting_position, length(vector), interval)] 
}

# We have k forms and j subscales, plus a TOT score for each form. Thus the list
# of all needed vectors will have a length of k*(j+1). To get this list, we use
# a nested mapping structure. On the inner call of map, the integer vector 1:5
# is the .x arg, to specify 5 starting positions (items 1-5), as the starting
# subset position for each of the five subscales. In the call of
# `nth_element()`, .x is the placeholder of the starting_position argument. Back
# to the inner map call, the .y argument is the place holder for the vector
# argument of `nth_element`. The .y argument is fed in by the outer map call.
# The interval argument is fixed at 5 for all subscales. On the inner map call,
# we need to also supply the `.y = .x` argument so that R knows that the .y
# argument of the inner map call is being supplied by the .x argument of the
# outer map call.

# the inner map call is wrapped in `splice()` which joins two lists into a
# single list. The first argument of `splice` is the list of 5 subscale vectors
# generated by the inner map call. The 2nd argument is TOT_item_names, the .x
# argument of the outer map call, Thus the 4-element list of "master" char vecs
# (the TOT item cols for each form), functions as the .y argument of the inner
# map call AND as the .x element of the splice call. Splice thus joins a list of
# 5 subscale vectors to the TOT vector, and the outer map call ensures that this
# splicing iterates four times, once for each form.

# finally, the list object is piped through `flatten()` to return a single flat
# list containing all 24 scale item vectors, in the required grouping order of
# all 6 vecs for one form, followed by all 6 vecs for the next form, and so on.
scale_item_names <- map(TOT_item_names_list,
                           ~ splice(map(1:5, ~ nth_element(.y, .x, 5), .y = .x), .x)) %>%
  flatten()

